/****** VEREIN Database - Clean Version ******/
-- This is a clean version of APPLICATION_H_101.sql with proper encoding

-- Create Database
CREATE DATABASE [VEREIN]
GO

USE [VEREIN]
GO

-- Set Database Options
ALTER DATABASE [VEREIN] SET COMPATIBILITY_LEVEL = 160
GO
ALTER DATABASE [VEREIN] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [VEREIN] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [VEREIN] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [VEREIN] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [VEREIN] SET ARITHABORT OFF 
GO
ALTER DATABASE [VEREIN] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [VEREIN] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [VEREIN] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [VEREIN] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [VEREIN] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [VEREIN] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [VEREIN] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [VEREIN] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [VEREIN] SET ALLOW_SNAPSHOT_ISOLATION ON 
GO
ALTER DATABASE [VEREIN] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [VEREIN] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [VEREIN] SET MULTI_USER 
GO

-- Create Schemas
CREATE SCHEMA [Bank]
GO
CREATE SCHEMA [Finanz]
GO
CREATE SCHEMA [Keytable]
GO
CREATE SCHEMA [Logs]
GO
CREATE SCHEMA [Mitglied]
GO
CREATE SCHEMA [Stammdaten]
GO
CREATE SCHEMA [Todesfall]
GO
CREATE SCHEMA [Verein]
GO
CREATE SCHEMA [Web]
GO
CREATE SCHEMA [Xbackups]
GO

-- Note: All tables will be created by Entity Framework Core migrations
-- This script only creates the database and schemas
-- Run: dotnet ef database update --project verein-api

ALTER DATABASE [VEREIN] SET READ_WRITE 
GO

